kind: pipeline
type: ssh
name: deploy-nginx
server:
  host:
    from_secret: ssh-hostname
  user:
    from_secret: ssh-username
  password:
    from_secret: ssh-password
  port: 36000

steps:
  - name: deploy-nginx
    image: alpine
    commands:
      - echo "Deploying nginx in Docker container"
      - echo "This is test from Jon"
